### ISSUE TITLE
Documentation -- hamming on strings of different lengths

### ISSUE THREAD

**Issue by mcahn** [rapidfuzz/python-Levenshtein#4]
The documentation here: https://maxbachmann.github.io/Levenshtein/levenshtein.html states:

```
Levenshtein.hamming(s1, s2, *, processor=None, score_cutoff=None)

Raises:
    ValueError – If s1 and s2 have a different length

```

However it seems to really add the extraneous characters to the returned distance:

```
>>> Levenshtein.hamming('atcgatcgatcg', 'atcgatcgatcgtttt')
4
```
-- Matthew Cahn

**Comment by mcahn** [comment]
Come to think of it, I don't know if the documentation is incorrect, or if the code is supposed to do what the documentation says.

-- Matthew

**Comment by maxbachmann** [comment]
A mixture of both. Historically the hamming distance in `rapidfuzz` did not accept strings of different length. This was changed in https://github.com/maxbachmann/RapidFuzz/releases/tag/v3.1.0 which added a `pad` argument which controls whether two sequences of different length should be padded with dummy characters which never match or fail with a ValueError. The default for this was set to `True`, since it usually is not all that helpful for the metric to fail in this case.

I think it would probably make sense to update implementation + docs in Levenshtein / python-Levenshtein in the same way :thinking:

**Comment by mcahn** [comment]
Thanks for the reply.  Since I'm only comparing strings of the same length,
I don't have a strong feeling on how it behaves with strings of different
lengths. Although I suppose if I wrote my code incorrectly and walked off
the end of the string I'm trying to match against, a ValueError would be
good.  In any case, thanks for providing this module.

-- Matthew

**Comment by maxbachmann** [comment]
The behaviour does now depend on the `pad` argument similar to the way this is handled in rapidfuzz.
